import { StyleSheet, Platform, StatusBar, I18nManager } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#001529',
    paddingTop: Platform.OS === 'ios' ? 44 : (Platform.OS === 'android' ? StatusBar.currentHeight : 0),
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 48,
  },
  mainCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: 16,
    paddingBottom: 14,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  rangeText: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.68)',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  controlsRow: {
    marginTop: 10,
    flexDirection: I18nManager.isRTL ? 'row' : 'row-reverse',
  },
  secondaryControlButton: {
    minWidth: 130,
    minHeight: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0,212,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.46)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryControlButtonText: {
    color: '#d9f7ff',
    fontSize: 13,
    fontWeight: '700',
  },
  groupCard: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  groupHeaderButton: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  groupHeaderMain: {
    flex: 1,
    alignItems: 'flex-start',
  },
  groupName: {
    color: '#f2fbff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  groupMetaText: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.66)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  groupInactiveText: {
    marginTop: 4,
    color: '#ff9f9f',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  groupAttendanceWrap: {
    minWidth: 102,
    borderRadius: 12,
    backgroundColor: 'rgba(0,212,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.32)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  groupAttendanceLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 11,
    textAlign: 'center',
  },
  groupAttendanceValue: {
    marginTop: 2,
    color: '#8befff',
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  groupAttendanceRatio: {
    color: 'rgba(255,255,255,0.74)',
    fontSize: 12,
    textAlign: 'center',
  },
  groupExpandHint: {
    marginTop: 4,
    color: '#d3f7ff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  childrenPanel: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(0, 21, 41, 0.38)',
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  childRow: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  childAttendanceWrap: {
    minWidth: 84,
    alignItems: 'center',
  },
  childAttendanceValue: {
    color: '#8ce8ff',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  childAttendanceRatio: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: 'center',
  },
  childMissedText: {
    marginTop: 2,
    color: '#ffabab',
    fontSize: 12,
    textAlign: 'center',
  },
  childMetaWrap: {
    flex: 1,
    alignItems: 'flex-start',
  },
  childName: {
    color: '#ecfaff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  childMetaText: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.66)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  listStateText: {
    marginTop: 10,
    color: 'rgba(255,255,255,0.66)',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  errorText: {
    marginTop: 10,
    color: '#ff9b9b',
    fontSize: 14,
    alignSelf: 'stretch',
    width: '100%',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
});

export default styles;
