import { StyleSheet, Platform, StatusBar, I18nManager } from 'react-native';
import { colors, shadows } from '../theme/tokens';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bgDeep,
    paddingTop: Platform.OS === 'ios' ? 44 : (Platform.OS === 'android' ? StatusBar.currentHeight : 0),
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 48,
  },
  topHeaderRow: {
    paddingHorizontal: 16,
    paddingVertical: 2,
    marginTop: 0,
    marginBottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    zIndex: 12,
  },
  topHeaderTextWrap: {
    alignItems: 'flex-end',
  },
  topHeaderTitle: {
    color: '#f4fcff',
    fontSize: 24,
    fontWeight: '800',
    textShadowColor: 'rgba(0, 212, 255, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.26)',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  logoutButtonText: {
    color: '#e6f6ff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  mainCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: 16,
    paddingBottom: 18,
    ...shadows.glowPrimary,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  statsRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    minHeight: 92,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  statCardCool: {
    backgroundColor: 'rgba(0, 212, 255, 0.14)',
  },
  statCardWarm: {
    backgroundColor: 'rgba(255, 163, 92, 0.14)',
  },
  statNumber: {
    fontSize: 32,
    fontWeight: '800',
  },
  statNumberCool: {
    color: '#75e8ff',
  },
  statNumberWarm: {
    color: '#ffc37d',
  },
  statLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 15,
    textAlign: 'center',
  },
  groupsTitle: {
    marginTop: 18,
  },
  actionsSubtitle: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.62)',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  actionCloud: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    rowGap: 12,
  },
  actionIconTile: {
    width: '31%',
    minWidth: 94,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingTop: 10,
    paddingBottom: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  actionIconTileDisabled: {
    opacity: 0.52,
  },
  actionIconOrb: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  actionIconOrbDisabled: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  actionIconGlyph: {
    fontSize: 23,
  },
  actionIconLabel: {
    marginTop: 8,
    color: '#ebf9ff',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  actionIconLabelDisabled: {
    color: 'rgba(255,255,255,0.6)',
  },
  actionTintSea: {
    backgroundColor: 'rgba(0, 212, 255, 0.12)',
  },
  actionTintLagoon: {
    backgroundColor: 'rgba(0, 184, 212, 0.12)',
  },
  actionTintSky: {
    backgroundColor: 'rgba(97, 189, 255, 0.11)',
  },
  actionTintFoam: {
    backgroundColor: 'rgba(133, 222, 255, 0.12)',
  },
  actionTintMint: {
    backgroundColor: 'rgba(86, 208, 194, 0.14)',
  },
  actionTintCoral: {
    backgroundColor: 'rgba(255, 173, 112, 0.12)',
  },
  actionOffsetA: {
    marginTop: 2,
  },
  actionOffsetC: {
    marginTop: 0,
  },
  actionOffsetD: {
    marginTop: -4,
  },
  actionOffsetE: {
    marginTop: 8,
  },
  actionOffsetG: {
    marginTop: 10,
  },
  actionOffsetI: {
    marginTop: 4,
  },
  listStateText: {
    marginTop: 12,
    color: 'rgba(255,255,255,0.66)',
    fontSize: 15,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementSectionWrap: {
    marginTop: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(0, 19, 39, 0.34)',
    padding: 10,
    width: '100%',
  },
  managementSectionTitle: {
    color: '#f3fbff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  input: {
    marginTop: 6,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(0, 21, 41, 0.52)',
    paddingHorizontal: 12,
    color: '#f0faff',
  },
  searchInput: {
    marginTop: 8,
    marginBottom: 4,
  },
  multilineInput: {
    minHeight: 88,
    height: 96,
    paddingTop: 10,
    paddingBottom: 10,
  },
  inputError: {
    borderColor: '#ff7878',
  },
  fieldErrorText: {
    marginTop: 4,
    color: '#ff9a9a',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  fieldHintText: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementEmptyText: {
    marginTop: 8,
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementRow: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    padding: 14,
    flexDirection: 'column',
    alignItems: 'stretch',
    width: '100%',
  },
  managementRowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: I18nManager.isRTL ? 'flex-end' : 'flex-start',
    columnGap: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    paddingTop: 10,
    marginTop: 6,
  },
  managementRowTextWrap: {
    width: '100%',
    alignItems: 'stretch',
    marginBottom: 6,
  },
  managementRowTitle: {
    color: '#f1fbff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementRowMeta: {
    marginTop: 2,
    color: '#9fd8f7',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementRowSubMeta: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  entityEditButton: {
    minWidth: 58,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.52)',
    backgroundColor: 'rgba(0,212,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  entityEditButtonText: {
    color: '#ddf7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  entityDeleteButton: {
    minWidth: 58,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,110,110,0.55)',
    backgroundColor: 'rgba(255,110,110,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  entityDeleteButtonText: {
    color: '#ffd4d4',
    fontSize: 12,
    fontWeight: '700',
  },
  groupChildrenToggle: {
    marginTop: 8,
    alignSelf: 'flex-end',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.35)',
    backgroundColor: 'rgba(0,212,255,0.12)',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  groupChildrenToggleText: {
    color: '#d9f7ff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  groupChildrenDropdownPanel: {
    marginTop: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(0, 21, 41, 0.4)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    width: '100%',
  },
  groupChildrenName: {
    color: '#d9f0ff',
    fontSize: 12,
    marginTop: 2,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  groupChildrenEmptyText: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 10, 24, 0.78)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(2, 26, 49, 0.95)',
    padding: 14,
    maxHeight: '90%',
  },
  modalTitle: {
    color: '#f3fcff',
    fontSize: 24,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  modalSubtitle: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.64)',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  fieldLabel: {
    marginTop: 10,
    color: '#ccedff',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  dropdownTrigger: {
    marginTop: 6,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(0, 21, 41, 0.52)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownTriggerDisabled: {
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  dropdownTriggerError: {
    borderColor: '#ff8a8a',
  },
  dropdownText: {
    flex: 1,
    color: '#eefbff',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  dropdownPlaceholderText: {
    color: 'rgba(255,255,255,0.58)',
  },
  dropdownArrow: {
    marginLeft: 8,
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    fontWeight: '700',
  },
  dropdownPanel: {
    marginTop: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(2, 31, 56, 0.97)',
    maxHeight: 190,
  },
  dropdownScroll: {
    maxHeight: 188,
  },
  dropdownOption: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  dropdownOptionDisabled: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  dropdownOptionActive: {
    backgroundColor: 'rgba(0,212,255,0.18)',
  },
  dropdownOptionText: {
    color: '#eefaff',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  dropdownOptionTextActive: {
    color: '#d3f6ff',
    fontWeight: '700',
  },
  dropdownOptionTextDisabled: {
    color: 'rgba(255,255,255,0.56)',
  },
  dropdownOptionMeta: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.64)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  dropdownOptionMetaDisabled: {
    color: 'rgba(255,255,255,0.48)',
  },
  aiSectionTitle: {
    marginTop: 12,
    color: '#def6ff',
    fontSize: 15,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  aiRecommendationCard: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.34)',
    backgroundColor: 'rgba(0,212,255,0.12)',
    padding: 12,
  },
  aiRecommendationTitle: {
    color: '#e8fbff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  aiRecommendationMeta: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.78)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  aiRecommendationFallback: {
    marginTop: 6,
    color: '#ffd89b',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  aiRecommendationReasoning: {
    marginTop: 8,
    color: 'rgba(255,255,255,0.84)',
    fontSize: 13,
    lineHeight: 18,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  aiApplyButtonShell: {
    marginTop: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  aiApplyButton: {
    minHeight: 44,
  },
  aiApplyButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  modalActionsWrap: {
    marginTop: 12,
  },
  modalPrimaryButtonShell: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  modalPrimaryButton: {
    minHeight: 48,
  },
  modalPrimaryButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  modalCancelButton: {
    marginTop: 10,
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  modalCancelButtonText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 15,
    fontWeight: '600',
  },
  skillChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
    marginTop: 2,
  },
  skillChip: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  skillChipStrengthActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.25)',
    borderColor: '#22c55e',
  },
  skillChipWeaknessActive: {
    backgroundColor: 'rgba(239, 68, 68, 0.25)',
    borderColor: '#ef4444',
  },
  skillChipDisabled: {
    opacity: 0.35,
  },
  skillChipText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11.5,
    fontWeight: '600',
  },
  skillChipTextActive: {
    color: '#ffffff',
  },
  skillChipTextDisabled: {
    color: 'rgba(255, 255, 255, 0.4)',
  },
  personalGoalsSection: {
    alignSelf: 'stretch',
    marginTop: 10,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    width: '100%',
  },
  personalGoalItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
    width: '100%',
    gap: 8,
  },
  personalGoalIcon: {
    fontSize: 16,
    marginTop: 2,
  },
  personalGoalTextWrap: {
    flex: 1,
  },
  personalGoalType: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  personalGoalTypeStrength: {
    color: '#22c55e',
  },
  personalGoalTypeWeakness: {
    color: '#ef4444',
  },
  personalGoalText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 13,
    lineHeight: 19,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  managementListContainer: {
    maxHeight: 380,
    marginHorizontal: -8,
  },
  managementListContent: {
    paddingHorizontal: 14,
    paddingBottom: 8,
  },
});

export default styles;