// Styles are now co-located in InstructorHomepage.js to match the Homepage.js pattern.
// This file is kept for backward-compatibility if other screens import from it.

import { StyleSheet } from 'react-native';
import { colors, spacing, radius, typography, shadows } from '../theme/tokens';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bgDeep,
  },
  screenContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
  },
  surfaceCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    padding: spacing.lg,
  },
  helperCard: {
    marginTop: spacing.lg,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    padding: spacing.lg,
  },
  helperTitle: {
    color: '#00d4ff',
    fontSize: 14,
    fontWeight: '700',
    writingDirection: 'rtl',
    textAlign: 'right',
    marginBottom: spacing.xs,
  },
  helperText: {
    color: 'rgba(255, 255, 255, 0.65)',
    fontSize: 13,
    lineHeight: 20,
    writingDirection: 'rtl',
    textAlign: 'right',
  },
  rowRightIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 212, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowRightIconText: {
    color: '#00d4ff',
    fontWeight: '800',
  },
  profileAvatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'rgba(0, 212, 255, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },
  profileAvatarText: {
    color: '#00d4ff',
    fontSize: 44,
    fontWeight: '800',
  },
  profileName: {
    marginTop: spacing.sm,
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
    writingDirection: 'rtl',
    textAlign: 'center',
  },
  profileMeta: {
    marginTop: spacing.xs,
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.6)',
    writingDirection: 'rtl',
    textAlign: 'center',
  },
  headerDate: {
    marginTop: spacing.sm,
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.65)',
    fontSize: 14,
    fontWeight: '600',
    writingDirection: 'rtl',
  },
  chipRow: {
    marginTop: spacing.lg,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  chip: {
    flex: 1,
    marginHorizontal: spacing.xs,
    borderRadius: radius.md,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(0, 212, 255, 0.1)',
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#00d4ff',
    writingDirection: 'rtl',
  },
  mainCard: {
    marginTop: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    ...shadows.glowPrimary,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: typography.title,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  groupRow: {
    marginTop: spacing.md,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  cancelButton: {
    backgroundColor: 'rgba(231, 76, 60, 0.2)',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    minWidth: 96,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(231, 76, 60, 0.35)',
  },
  cancelButtonText: {
    color: '#ff6b6b',
    fontWeight: '600',
    fontSize: 13,
    writingDirection: 'rtl',
  },
  groupTextWrap: {
    alignItems: 'flex-end',
    flex: 1,
    marginRight: 8,
  },
  groupTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    writingDirection: 'rtl',
  },
  groupSubtitle: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 13,
    marginTop: 2,
    writingDirection: 'rtl',
  },
  bottomActions: {
    marginTop: spacing.lg,
    gap: 10,
  },
  actionButton: {
    borderRadius: radius.md,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: spacing.xs,
  },
  actionButtonText: {
    color: '#001529',
    fontSize: 18,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
});

export default styles;
