import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';
import { colors, shadows } from '../theme/tokens';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgDeep,
  },
  surfaceGlow: {
    ...StyleSheet.absoluteFillObject,
  },
  waveContainer: {
    position: 'absolute',
    bottom: 0,
    left: (width - 2400) / 2,
    width: 2400,
    height: 150,
    zIndex: 0,
  },

  navbar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    paddingTop: Platform.OS === 'ios' ? 44 : (StatusBar.currentHeight || 20) + 6,
    paddingBottom: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  navIconBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutBtnText: {
    color: '#def6ff',
    fontSize: 22,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  navCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navLogo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navLogoEmoji: {
    fontSize: 14,
  },
  navTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellWrap: {
    minWidth: 80,
    height: 36,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  navBellContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  navBellLabel: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  navBell: {
    fontSize: 18,
  },
  navBadge: {
    position: 'absolute',
    top: -7,
    right: -9,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
    textAlign: 'center',
    writingDirection: 'rtl',
  },

  scrollContent: {
    paddingTop: 120,
    paddingBottom: 56,
  },
  hero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: '8%',
    paddingTop: 8,
    paddingBottom: 6,
  },
  heroTitle: {
    fontSize: 27,
    fontWeight: '800',
    color: '#00d4ff',
    textAlign: 'center',
    writingDirection: 'rtl',
    textShadowColor: 'rgba(0, 212, 255, 0.28)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  heroSubtitle: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  heroChildName: {
    marginTop: 10,
    color: '#e7fbff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    writingDirection: 'rtl',
  },

  section: {
    marginTop: 20,
    paddingHorizontal: '5%',
    zIndex: 10,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: '700',
    color: '#fff',
    writingDirection: 'rtl',
  },
  glassCard: {
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  exercisePickerTitle: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 10,
  },
  exercisePickerWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  exerciseChip: {
    minWidth: '48%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  exerciseChipActive: {
    borderColor: '#00d4ff',
    backgroundColor: 'rgba(0, 212, 255, 0.16)',
  },
  exerciseChipPercent: {
    color: '#d4e2ea',
    fontSize: 18,
    fontWeight: '900',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  exerciseChipPercentActive: {
    color: '#d6f7ff',
  },
  exerciseChipText: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 4,
  },
  exerciseChipTextActive: {
    color: '#ffffff',
  },
  cardMeta: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 12,
  },
  stateText: {
    color: 'rgba(255,255,255,0.66)',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  errorText: {
    color: '#ff9a8b',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 6,
    fontSize: 14,
  },
  childPickerLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
  },
  childPickerStateText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  childChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  childChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  childChipActive: {
    borderColor: 'rgba(0,212,255,0.7)',
    backgroundColor: 'rgba(0,212,255,0.22)',
  },
  childChipText: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    fontWeight: '600',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  childChipTextActive: {
    color: '#d9f8ff',
    fontWeight: '800',
  },

  progressItem: {
    marginBottom: 12,
  },
  progressLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
    gap: 8,
  },
  progressLabel: {
    color: '#e8f7ff',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    fontSize: 14,
    writingDirection: 'rtl',
    flexShrink: 1,
  },
  progressPercent: {
    color: 'rgba(255,255,255,0.7)',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    fontSize: 13,
    minWidth: 38,
    writingDirection: 'rtl',
  },
  progressTrack: {
    height: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
    flexDirection: 'row-reverse',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#00b8d4',
  },

  commentItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.07)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  commentDate: {
    color: '#8aeaff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
  },
  commentText: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 21,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },

  actionsSection: {
    marginTop: 18,
    paddingHorizontal: '5%',
    gap: 10,
    zIndex: 10,
  },
  summaryButtonShell: {
    borderRadius: 16,
    overflow: 'hidden',
    ...shadows.glowPrimary,
  },
  summaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
  },
  summaryButtonText: {
    color: '#eff9ff',
    fontSize: 15,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  summaryNoticeText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 2,
    lineHeight: 20,
  },
  summaryErrorText: {
    color: '#ffb19f',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 2,
    lineHeight: 20,
  },
  summaryBox: {
    marginTop: 2,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summarySourceLabel: {
    color: '#8aeaff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 6,
  },
  summaryText: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 14,
    lineHeight: 22,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  summaryLinesWrap: {
    marginTop: 2,
  },
  summaryLineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  summaryLineBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0, 212, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(138, 234, 255, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 1,
  },
  summaryLineBadgeText: {
    color: '#b8f4ff',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  summaryLineText: {
    flex: 1,
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    lineHeight: 23,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  summaryLineLast: {
    marginBottom: 0,
  },

  actionButtonShell: {
    borderRadius: 16,
    overflow: 'hidden',
    ...shadows.glowPrimary,
  },
  actionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
  },
  actionButtonText: {
    color: '#eff9ff',
    fontSize: 16,
    fontWeight: '700',
    writingDirection: 'rtl',
  },

  backButton: {
    marginTop: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 12,
    alignItems: 'center',
  },
  backButtonText: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 14,
    fontWeight: '700',
    writingDirection: 'rtl',
  },

  footer: {
    marginTop: 30,
    paddingTop: 10,
    alignItems: 'center',
    zIndex: 10,
  },
  footerCopy: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 11,
    writingDirection: 'rtl',
    textAlign: 'center',
  },
});

export default styles;
