import { StyleSheet, Dimensions, Platform, StatusBar, I18nManager } from 'react-native';
import { colors, shadows } from '../theme/tokens';

const { width } = Dimensions.get('window');

function clamp(min, val, max) {
  return Math.min(Math.max(val, min), max);
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgDeep },
  scrollContent: { paddingTop: 70, paddingBottom: 60 },

  /* Waves & Bubbles */
  waveContainer: {
    position: 'absolute', bottom: 0, left: (width - 2400) / 2,
    width: 2400, height: 150, zIndex: 0,
  },

  /* ג”€ג”€ Navbar ג”€ג”€ */
  navbar: {
    position: 'absolute', top: 0, left: 0, right: 0,
    paddingTop: Platform.OS === 'ios' ? 44 : (StatusBar.currentHeight || 20) + 6,
    paddingBottom: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  navIconBtn: {
    width: 36, height: 36,
    justifyContent: 'center', alignItems: 'center',
  },
  logoutBtn: {
    minWidth: 76,
    height: 32,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  logoutBtnText: {
    color: '#f3fbff',
    fontSize: 11,
    fontWeight: '800',
    writingDirection: 'rtl',
  },
  navCenter: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  navLogo: {
    width: 28, height: 28, borderRadius: 14,
    justifyContent: 'center', alignItems: 'center',
  },
  navLogoEmoji: { fontSize: 14 },
  navTitle: {
    color: '#fff', fontSize: 16, fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellWrap: {
    minWidth: 80,
    height: 36,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  navBellContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  navBellLabel: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  navBell: { fontSize: 18 },
  navBadge: {
    position: 'absolute',
    top: -7,
    right: -9,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    elevation: 3,
  },
  navBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
    textAlign: 'center',
  },

  /* ג”€ג”€ Hero ג”€ג”€ */
  hero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: '8%',
    paddingTop: 30,
    paddingBottom: 10,
    zIndex: 10,
  },
  heroWelcome: {
    fontSize: clamp(26, width * 0.075, 34),
    fontWeight: '300',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    writingDirection: 'rtl',
    marginBottom: 6,
  },
  heroChildRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  heroChildLabel: {
    fontSize: clamp(20, width * 0.06, 28),
    fontWeight: '400',
    color: 'rgba(255,255,255,0.75)',
    writingDirection: 'rtl',
  },
  heroChildName: {
    fontSize: clamp(28, width * 0.08, 38),
    fontWeight: '800',
    color: '#00d4ff',
    textShadowColor: 'rgba(0,212,255,0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 18,
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ Section shared ג”€ג”€ */
  section: {
    marginTop: 36,
    paddingHorizontal: '5%',
    zIndex: 10,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 18,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 22, fontWeight: '700',
    color: '#fff',
    writingDirection: 'rtl',
  },
  selectorWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  selectorChip: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  selectorChipActive: {
    backgroundColor: 'rgba(0,212,255,0.2)',
    borderColor: 'rgba(0,212,255,0.55)',
  },
  selectorChipText: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 14,
    fontWeight: '600',
    writingDirection: 'rtl',
  },
  selectorChipTextActive: {
    color: '#d9f8ff',
  },
  selectorHelperText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 13,
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ Activity cards ג”€ג”€ */
  activityCard: {
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  activityAccent: {
    position: 'absolute',
    right: 0, top: 12, bottom: 12,
    width: 3, borderRadius: 3,
  },
  activityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  activityHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  activityIconBgMini: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  activityIconMini: {
    fontSize: 16,
  },
  activityTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  activityDateBadge: {
    backgroundColor: 'rgba(0,212,255,0.12)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.2)',
  },
  activityDate: {
    color: '#00d4ff',
    fontSize: 12,
    fontWeight: '700',
  },
  activityContent: {
    paddingStart: 42, // Aligns with the text start after the mini icon
    marginBottom: 12,
  },
  activityDesc: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    lineHeight: 18,
  },
  activityDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginHorizontal: 4,
    marginBottom: 12,
  },
  activityFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end', // Aligns the button to the left side in RTL (end)
  },
  activityReportBtn: {
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.4)',
  },
  activityReportBtnGradient: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityReportBtnText: {
    color: '#d7f6ff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ Upcoming lessons ג”€ג”€ */
  lessonCard: {
    marginBottom: 12,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 14,
  },
  lessonHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  lessonTypeBadge: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
  },
  lessonTypeBadgePrivate: {
    backgroundColor: 'rgba(0,212,255,0.16)',
    borderColor: 'rgba(0,212,255,0.4)',
  },
  lessonTypeBadgeGroup: {
    backgroundColor: 'rgba(0,184,212,0.16)',
    borderColor: 'rgba(0,184,212,0.4)',
  },
  lessonTypeBadgeText: {
    color: '#d9f8ff',
    fontSize: 11,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  lessonStatusBadge: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  lessonStatusBadgeText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 11,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  lessonPrimaryText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
  },
  lessonSecondaryText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 2,
  },
  lessonDateLine: {
    color: '#9eefff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 5,
  },
  lessonNotes: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    lineHeight: 18,
  },
  lessonMetricText: {
    marginTop: 5,
    color: '#ffd670',
    fontSize: 13,
    fontWeight: '600',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ Instructor card ג”€ג”€ */
  instructorsListWrap: {
    gap: 12,
  },
  instructorCard: {
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    gap: 14,
  },
  instructorInfo: {
    flex: 1,
  },
  instructorName: {
    color: '#fff', fontSize: 17, fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right', writingDirection: 'rtl',
  },
  instructorRole: {
    color: 'rgba(255,255,255,0.5)', fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right', writingDirection: 'rtl',
    marginTop: 3,
  },
  instructorChildrenLabel: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 6,
  },
  chatBtn: {
    borderRadius: 14,
    overflow: 'visible',
    position: 'relative',
    zIndex: 4,
    elevation: 4,
  },
  chatBtnGradient: {
    width: 44, height: 44,
    justifyContent: 'center', alignItems: 'center',
    borderRadius: 14,
    position: 'relative',
  },
  chatBtnIcon: { fontSize: 20 },
  chatBtnBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    elevation: 3,
  },
  chatBtnBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 12,
  },
  scheduleHintText: {
    marginTop: 12,
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
    lineHeight: 19,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ Action buttons ג”€ג”€ */
  actionsSection: {
    marginTop: 34,
    paddingHorizontal: '5%',
    gap: 12,
    zIndex: 10,
  },
  actionBtnOuter: {
    borderRadius: 18,
    overflow: 'hidden',
    ...shadows.glowPrimary,
  },
  actionBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 22,
    borderRadius: 18,
    gap: 14,
  },
  actionBtnIcon: {
    fontSize: 22,
  },
  actionBtnLabel: {
    flex: 1,
    color: '#001529',
    fontSize: 16,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  actionBtnArrow: {
    color: 'rgba(0,21,41,0.5)',
    fontSize: 20,
    fontWeight: '700',
  },

  /* ג”€ג”€ Footer ג”€ג”€ */
  footer: {
    marginTop: 60,
    paddingTop: 30,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    zIndex: 10,
  },
  footerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  footerEmoji: { fontSize: 22 },
  footerBrandText: { color: '#fff', fontSize: 20, fontWeight: '600' },
  footerText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    marginBottom: 8,
    textAlign: 'center',
  },
  footerCopy: { color: 'rgba(255,255,255,0.3)', fontSize: 11 },

  /* ג”€ג”€ Lesson report modal ג”€ג”€ */
  reportModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 21, 41, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  reportModalCard: {
    width: '100%',
    maxHeight: '90%',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  reportModalTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 10,
  },
  reportModalMetaLine: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
  },
  reportModalSectionTitle: {
    color: '#d7f6ff',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginTop: 12,
    marginBottom: 7,
  },
  reportModalEmptyText: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 8,
  },
  reportMetricRow: {
    marginBottom: 9,
  },
  reportMetricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  reportMetricLabel: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
    flexShrink: 1,
  },
  reportMetricValue: {
    color: '#a9edff',
    fontSize: 12,
    fontWeight: '700',
    marginRight: 8,
  },
  reportMetricTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
    flexDirection: 'row-reverse',
  },
  reportMetricFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#00b7d6',
  },
  reportCommentBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  reportCommentText: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  reportModalCloseButton: {
    marginTop: 14,
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor: 'rgba(0,212,255,0.24)',
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.5)',
    paddingVertical: 10,
  },
  reportModalCloseButtonText: {
    color: '#d7f6ff',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    writingDirection: 'rtl',
  },

  /* ג”€ג”€ ACM guide modal ג”€ג”€ */
  acmGuideModalCard: {
    width: '100%',
    maxHeight: '90%',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  acmGuideTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 8,
  },
  acmGuideIntro: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 10,
  },
  acmGuideScroll: {
    maxHeight: 460,
  },
  acmGuideScrollContent: {
    paddingBottom: 8,
  },
  acmGuideSection: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  acmGuideSectionTitle: {
    color: '#d7f6ff',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 6,
  },
  acmGuideBullet: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
  },
  acmGuideSourceNote: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,212,255,0.35)',
    backgroundColor: 'rgba(0,212,255,0.11)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  acmGuideSourceText: {
    color: '#d7f6ff',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  acmGuideCloseButton: {
    marginTop: 12,
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor: 'rgba(255,207,91,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,207,91,0.5)',
    paddingVertical: 10,
  },
  acmGuideCloseButtonText: {
    color: '#fff5cf',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  childFilterContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    paddingHorizontal: 16,
  },
  childFilterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  childFilterChipActive: {
    backgroundColor: 'rgba(0, 212, 255, 0.25)',
    borderColor: 'rgba(0, 212, 255, 0.6)',
  },
  childFilterText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  childFilterTextActive: {
    color: '#d9f8ff',
    fontWeight: '800',
  },
});

export default styles;
