import { Platform, StatusBar, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#001a33',
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },

  navbar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    paddingTop: Platform.OS === 'ios' ? 44 : (StatusBar.currentHeight || 20) + 6,
    paddingBottom: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  logoutBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutBtnText: {
    color: '#def6ff',
    fontSize: 22,
    textAlign: 'center',
  },
  navCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navLogo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navLogoEmoji: {
    fontSize: 14,
  },
  navTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellWrap: {
    minWidth: 80,
    height: 36,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  navBellContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  navBellLabel: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  navBellIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  navBell: {
    fontSize: 18,
  },
  navBadge: {
    position: 'absolute',
    top: -7,
    right: -9,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
    textAlign: 'center',
  },

  scrollContent: {
    paddingTop: 120,
    paddingBottom: 56,
  },
  hero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: '8%',
    paddingTop: 10,
    paddingBottom: 6,
  },
  heroTitle: {
    fontSize: 27,
    fontWeight: '800',
    color: '#00d4ff',
    textAlign: 'center',
    writingDirection: 'rtl',
    textShadowColor: 'rgba(0, 212, 255, 0.28)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  heroSubtitle: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: 'center',
    writingDirection: 'rtl',
  },

  section: {
    marginTop: 16,
    paddingHorizontal: '5%',
  },
  summaryCard: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryTitle: {
    color: '#e8f7ff',
    fontSize: 16,
    fontWeight: '800',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 6,
  },
  summaryLine: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 2,
  },

  childFilterLabel: {
    color: '#e8f7ff',
    fontSize: 15,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginBottom: 8,
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  childChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  childChipActive: {
    borderColor: 'rgba(0,212,255,0.7)',
    backgroundColor: 'rgba(0,212,255,0.22)',
  },
  childChipText: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    fontWeight: '600',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  childChipTextActive: {
    color: '#d9f8ff',
    fontWeight: '800',
  },

  stateWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    marginTop: 6,
  },
  stateText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  errorText: {
    color: '#ff9a8b',
    fontSize: 14,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },

  childSectionCard: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  childSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  childSectionTitle: {
    color: '#e8f7ff',
    fontSize: 17,
    fontWeight: '800',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  childSectionCount: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'right' : 'left',
    writingDirection: 'rtl',
  },
  emptyChildText: {
    color: 'rgba(255,255,255,0.66)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },

  lessonCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(0, 21, 41, 0.45)',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginBottom: 8,
  },
  lessonHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  lessonDate: {
    color: '#d9f8ff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
  },
  lessonTypeBadge: {
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderWidth: 1,
  },
  lessonTypeBadgePrivate: {
    backgroundColor: 'rgba(0,212,255,0.16)',
    borderColor: 'rgba(0,212,255,0.4)',
  },
  lessonTypeBadgeGroup: {
    backgroundColor: 'rgba(0,184,212,0.16)',
    borderColor: 'rgba(0,184,212,0.4)',
  },
  lessonTypeBadgeText: {
    color: '#d9f8ff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  lessonLine: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 2,
  },
  lessonNotes: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    textAlign: Platform.OS === 'ios' ? 'left' : 'right',
    writingDirection: 'rtl',
    marginTop: 4,
    lineHeight: 17,
  },
});

export default styles;
